In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
#Answer 1: Yes there is a difference
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
#Answer 2:
for x in np.nditer(array_list):
    print("numpy",type(x))
for x in list_:
    print("normal array",type(x))

numpy <class 'numpy.ndarray'>
numpy <class 'numpy.ndarray'>
numpy <class 'numpy.ndarray'>
numpy <class 'numpy.ndarray'>
numpy <class 'numpy.ndarray'>
normal array <class 'str'>
normal array <class 'str'>
normal array <class 'str'>
normal array <class 'str'>
normal array <class 'str'>


In [5]:
#Answer 3: Yes there is difference
for x in np.nditer(array_list):
    print("numpy",type(x))
for x in list_:
    print("normal array",type(x))

numpy <class 'numpy.ndarray'>
numpy <class 'numpy.ndarray'>
numpy <class 'numpy.ndarray'>
numpy <class 'numpy.ndarray'>
numpy <class 'numpy.ndarray'>
normal array <class 'str'>
normal array <class 'str'>
normal array <class 'str'>
normal array <class 'str'>
normal array <class 'str'>


In [7]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [8]:
#Answer 4:
print(num_array.shape)
print(num_array.size)

(2, 3)
6


In [9]:
#Answer 5:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#Answer 6
a = np.diag([1,1,1,1,1])
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
